<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tablet_gui</name>
  <version>0.0.0</version>
  <description>Launches the GUI for the OARBot tablet</description>
  <maintainer email="oconna4@rpi.edu">Aidan O'Connor</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>kinova_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
