Section "ServerLayout"
    Identifier "HeadlessLayout"
    Screen 2 "Screen2"
EndSection

Section "Module"
    Load "glx"
EndSection

Section "Device"
    Identifier "IntelDevice"
    Driver "intel"

    BusID "PCI:0:2:0"
    
    Option "AccelMethod" "sna"
    Option "DRI" "3"
EndSection

Section "Monitor"
    Identifier "IntelMonitor"
    HorizSync 30-80
    VertRefresh 50-75
EndSection

Section "Screen"
    Identifier "Screen2"
    Device "IntelDevice"
    Monitor "IntelMonitor"
    DefaultDepth 24

    SubSection "Display"
        Depth 24
        Virtual 1280 800
    EndSubSection
EndSection