name: CI
on:
  push:
    paths:
      - "src/**"
    branches:
      - main
  pull_request:

jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest
    steps:
      # - name: Setup ROS2 Jazzy Environment
      #   uses: ros-tooling/setup-ros@v0.7
      #   with:
      #     required-ros-distributions: jazzy

      - name: Checkout packages.repos
        uses: actions/checkout@v7
        with:
          sparse-checkout: |
            packages.repos
            scripts/install-azure-kinect-drivers.sh
          sparse-checkout-cone-mode: false

      - name: Download and Install Azure Kinect Drivers
        run: sudo /bin/bash $GITHUB_WORKSPACE/scripts/install-azure-kinect-drivers.sh

      # - name: List ROS2 packages
      #   run: source /opt/ros/jazzy/setup.sh && ros2 pkg list

      - name: CI
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: jazzy
          vcs-repo-file-url: $GITHUB_WORKSPACE/packages.repos