name: Lint
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
    branches:
      - main
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, flake8, mypy, pep257, pep8, xmllint]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: List packages
      id: list_packages
      run: echo "packages=$(colcon list --names-only | tr '\n' ' ')" >> "$GITHUB_OUTPUT"


    - name: Lint
      uses: ros-tooling/action-ros-lint@0.1
      with:
        linter: ${{ matrix.linter }}
        package-name: ${{ steps.list_packages.outputs.packages }}
        distribution: jazzy