name: Lint
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
    branches:
      - main
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [flake8, pep257, cpplint, lint_cmake, copyright, xmllint]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run Linter
        run: |
          ament_${matrix.linter}