name: Test Documentation Deployment

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docusaurus/**"
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            docusaurus

      - name: Copy docs to workspace root
        run: cp -a $GITHUB_WORKSPACE/docusaurus/. $GITHUB_WORKSPACE/

      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test build website
        run: npm run build